CREATE TABLE AUTHOR(
	AUTHOR_ID NUMBER(*, 0) PRIMARY KEY,
	AUTHOR_NAME NVARCHAR(30) NOT NULL
);

CREATE TABLE COMMENTS(
  COMMENT_ID NUMBER(*, 0) PRIMARY KEY,
  NEWS_ID NUMBER(20) NOT NULL,
  COMMENT_TEXT NVARCHAR2(100) NOT NULL,
  COMMENT_DATE DATE NOT NULL,
  CONSTRAINT fk_news_comments  FOREIGN KEY(NEWS_ID) REFERENCES NEWS(NEWS_ID)
);

CREATE TABLE NEWS(
  NEWS_ID NUMBER(*, 0) PRIMARY KEY,
  MAIN_TITLE NVARCHAR2(30) NOT NULL,
  SHORT_TITLE NVARCHAR2(100) NOT NULL,
  TEXT NVARCHAR2(2000) NOT NULL,
  PUBLIS_DATE DATE NOT NULL
);

CREATE TABLE TAG(
  TAG_ID NUMBER(*, 0) PRIMARY KEY,
  TAG_NAME NVARCHAR2(30) NOT NULL
);

CREATE TABLE NEWS_TAG(
  NEWS_ID NUMBER(*, 0) NOT NULL,
  TAG_ID NUMBER(*, 0) NOT NULL,
  CONSTRAINT 
  fk_news_news_tag  FOREIGN KEY(NEWS_ID) REFERENCES NEWS(NEWS_ID),
  CONSTRAINT 
  fk_tag_news_tag  FOREIGN KEY(TAG_ID) REFERENCES TAG(TAG_ID)
);

CREATE TABLE NEWS_AUTHOR(
  NEWS_ID NUMBER(*, 0) NOT NULL,
  AUTHOR_ID NUMBER(*, 0) NOT NULL,
  CONSTRAINT 
  fk_news_news_author  FOREIGN KEY(NEWS_ID) REFERENCES NEWS(NEWS_ID),
  CONSTRAINT 
  fk_author_news_author  FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
);